# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc37d60dcc87957c09594002e23e4f40161447f56eb29fcd87658ad4a9b8d42d3c826852b8b28086dacb9d89305d5d61b75147a731f7f7657994addf0a80fccc

test:
  secret_key_base: 44aa5b8b5c886ddfb9582e69c85fac08aa4bffcb98d61c7e4066962d91f2c77866d9ed4c69d7d24ed0eb9d4297a4474e2309120288f7d078134d87bf05b480d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
